version: '3.8'
services:
  cartservice:
    build:
      context: ./CartService
    ports:
      - "5001:80"

  customerservice:
    build:
      context: ./CustomerService
    ports:
      - "5002:80"

  importproductservice:
    build:
      context: ./ImportProductService
    ports:
      - "5003:80"

  managerservice:
    build:
      context: ./ManagerService
    ports:
      - "5004:80"

  orderservice:
    build:
      context: ./OrderService
    ports:
      - "5005:80"

  productservice:
    build:
      context: ./ProductService
    ports:
      - "5006:80"
