using BusinessObject.Models.Entity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessObject.SeedData
{
    public static class ProductImageSeedData
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProductImage>().HasData(
            new ProductImage { ProId = "KB001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717921892/Products/Keyboard/ywkxnxta6noyaojpmnrb.webp" },
            new ProductImage { ProId = "KB001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717921996/Products/Keyboard/pyttp822qidum7t1twrr.webp" },
            new ProductImage { ProId = "KB001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922015/Products/Keyboard/eui0euacsjqhpa6hrayt.webp" },
            new ProductImage { ProId = "KB001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922030/Products/Keyboard/wwwocxbhmhxhy0t9rvru.jpg" },
            new ProductImage { ProId = "KB002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922113/Products/Keyboard/fka2rubjgwdefmhvrdos.webp" },
            new ProductImage { ProId = "KB002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922190/Products/Keyboard/e9sawikerlz0kw2lquhl.webp" },
            new ProductImage { ProId = "KB002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922202/Products/Keyboard/jtqdkratpsxokxwkqjog.webp" },
            new ProductImage { ProId = "KB002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922216/Products/Keyboard/zg6ioknni2duvji2puok.webp" },
            new ProductImage { ProId = "KB003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922248/Products/Keyboard/hr7g8phxsb8xfybimmf7.webp" },
            new ProductImage { ProId = "KB003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922280/Products/Keyboard/jurcj10bdnr2pkjymujo.webp" },
            new ProductImage { ProId = "KB003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922294/Products/Keyboard/fjts0sokzhiva33he1az.webp" },
            new ProductImage { ProId = "KB003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922305/Products/Keyboard/fvu3swa7bh30m4nkkb18.webp" },
            new ProductImage { ProId = "KB004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922346/Products/Keyboard/vpkbhpxqjxbxzacshoia.webp" },
            new ProductImage { ProId = "KB004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922380/Products/Keyboard/u6zvauadyrerizetn59v.webp" },
            new ProductImage { ProId = "KB004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922420/Products/Keyboard/hlaf0rna1tgdcnwd9wyy.webp" },
            new ProductImage { ProId = "KB004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922435/Products/Keyboard/wc5rkr8zvd0bt1ih2ci7.webp" },
            new ProductImage { ProId = "KB005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922464/Products/Keyboard/tweavgjpejduj0v8fwv9.webp" },
            new ProductImage { ProId = "KB005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922476/Products/Keyboard/scu51fazdl6tlwosvjig.webp" },
            new ProductImage { ProId = "KB005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922488/Products/Keyboard/g5qkjacnjipkpnlh1ohf.webp" },
            new ProductImage { ProId = "KB005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922519/Products/Keyboard/bcithwfksf6tbk6i3ivi.webp" },
            new ProductImage { ProId = "KB005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922536/Products/Keyboard/p0bydvsaj7qkbgjt3xit.webp" },
            new ProductImage { ProId = "KB006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922553/Products/Keyboard/i0a6x04nx9yodis6ygwg.webp" },
            new ProductImage { ProId = "KB006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922578/Products/Keyboard/zmy1x4itrnpibw83tbvm.webp" },
            new ProductImage { ProId = "KB006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922603/Products/Keyboard/asbjbkvfnikenkwll156.webp" },
            new ProductImage { ProId = "KB006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922620/Products/Keyboard/vtr63ngchmblratpatqs.webp" },
            new ProductImage { ProId = "CT001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924769/Products/Controller/qutk9vonjj39mvlwehuf.webp" },
            new ProductImage { ProId = "CT001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924787/Products/Controller/fw45gyha5cgfmympydwb.webp" },
            new ProductImage { ProId = "CT001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924802/Products/Controller/zyzz156z9ii0fpe1bc6q.webp" },
            new ProductImage { ProId = "CT001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924811/Products/Controller/rbiyyqkrtsu7yp7fdivt.webp" },
            new ProductImage { ProId = "CT002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924824/Products/Controller/b7ovbngq6xeroykeas8j.webp" },
            new ProductImage { ProId = "CT002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924831/Products/Controller/fxysr9h7sn5hai0vvo3t.webp" },
            new ProductImage { ProId = "CT002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924841/Products/Controller/shmkoxpgunprcqjribhq.webp" },
            new ProductImage { ProId = "CT002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924846/Products/Controller/wzsg4qsbtctwfpyzfo1f.webp" },
            new ProductImage { ProId = "CT002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924853/Products/Controller/zutrmelcspchnoehlm5c.webp" },
            new ProductImage { ProId = "CT003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924877/Products/Controller/jxkhexqcllxwm65aurcb.webp" },
            new ProductImage { ProId = "CT003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924890/Products/Controller/jdmuulygohhnhfdny6d7.png" },
            new ProductImage { ProId = "CT003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924899/Products/Controller/xynykmjy1dclfd7zs9d4.png" },
            new ProductImage { ProId = "CT003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924907/Products/Controller/dopzxlhlstarzoqwtn5s.png" },
            new ProductImage { ProId = "CT003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924923/Products/Controller/mqzeyfkk6kzh1vom0our.png" },
            new ProductImage { ProId = "CT004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924936/Products/Controller/obyvnzjnya5sakdfba4q.webp" },
            new ProductImage { ProId = "CT004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924942/Products/Controller/jmgxuf8hxqjd6p5mxok2.webp" },
            new ProductImage { ProId = "CT004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924959/Products/Controller/e45f1h04byzdvdzk4zzo.webp" },
            new ProductImage { ProId = "CT004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924967/Products/Controller/ttpstsgf37d0i4vdlz6g.webp" },
            new ProductImage { ProId = "CT004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924980/Products/Controller/olodpx1jnxwydpnliyid.webp" },
            new ProductImage { ProId = "GC001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928907/Products/GamingChairs/z5hzmap76ivbbfxycj8b.webp" },
            new ProductImage { ProId = "GC001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928916/Products/GamingChairs/yoybyil1wyzdfcutq3qw.webp" },
            new ProductImage { ProId = "GC001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928925/Products/GamingChairs/syg6aqccmexvqsfjik3k.webp" },
            new ProductImage { ProId = "GC001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928937/Products/GamingChairs/djo58phlzad9xef5jijr.webp" },
            new ProductImage { ProId = "GC001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928945/Products/GamingChairs/jgsgzq1sscfwtqw6rduq.webp" },
            new ProductImage { ProId = "GC002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928968/Products/GamingChairs/ppf6kqt8src7nnkdhvnz.webp" },
            new ProductImage { ProId = "GC002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928975/Products/GamingChairs/x80o2ptqik8ivna21ecu.webp" },
            new ProductImage { ProId = "GC002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717928987/Products/GamingChairs/mrdgigbyi3saf394gmvm.webp" },
            new ProductImage { ProId = "GC003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929010/Products/GamingChairs/witqzgy8058bbnyreioi.webp" },
            new ProductImage { ProId = "GC003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929025/Products/GamingChairs/p5cpb5webp9v6b64dsbr.webp" },
            new ProductImage { ProId = "GC003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929034/Products/GamingChairs/mjux9kkppegkmnrmvqwx.webp" },
            new ProductImage { ProId = "GC003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929044/Products/GamingChairs/wgu48tvjujgjikp2tbfn.webp" },
            new ProductImage { ProId = "GC004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929057/Products/GamingChairs/dukw1cw1g3xprnpzg1z2.jpg" },
            new ProductImage { ProId = "GC004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929066/Products/GamingChairs/zymtywd00sezrnj2xhh4.jpg" },
            new ProductImage { ProId = "GC004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929080/Products/GamingChairs/lwqvttntlpzjic7cvyfk.jpg" },
            new ProductImage { ProId = "GC004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929086/Products/GamingChairs/yn4tfqxcatqlnseutebl.jpg" },
            new ProductImage { ProId = "GC004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929097/Products/GamingChairs/by0cq5p6hl253udygfgm.jpg" },
            new ProductImage { ProId = "KB007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922632/Products/Keyboard/sbnpr0e0y3ollge0lflw.webp" },
            new ProductImage { ProId = "KB007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922641/Products/Keyboard/yr2kcczh8duvnu02hofo.webp" },
            new ProductImage { ProId = "KB007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922677/Products/Keyboard/mn9a5w7umabkyg1tgplt.webp" },
            new ProductImage { ProId = "KB007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922660/Products/Keyboard/wcjmdpb9kwlfbucttj7d.webp" },
            new ProductImage { ProId = "KB008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922962/Products/Keyboard/vyikxjpzjegxqwln7blt.webp" },
            new ProductImage { ProId = "KB008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922972/Products/Keyboard/pjhqkyv1xlbanfcm4ctj.jpg" },
            new ProductImage { ProId = "KB008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717922989/Products/Keyboard/iyg3amady0wjixg6istg.webp" },
            new ProductImage { ProId = "KB008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923012/Products/Keyboard/wscqeir6g21ldtvuysz6.jpg" },
            new ProductImage { ProId = "KB008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923032/Products/Keyboard/ib0wnl8mvmjntzufgvah.webp" },
            new ProductImage { ProId = "KB009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923046/Products/Keyboard/hgbjc67rrx6pkbv1illm.webp" },
            new ProductImage { ProId = "KB009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923056/Products/Keyboard/idhz1fau2x98ju9dojcm.webp" },
            new ProductImage { ProId = "KB009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923071/Products/Keyboard/gaapkk1sq6km9ub8d6om.webp" },
            new ProductImage { ProId = "KB009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923084/Products/Keyboard/ynecq3efezwblellfhoa.webp" },
            new ProductImage { ProId = "KB009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923097/Products/Keyboard/fxczch4zcyphznps6dik.webp" },
            new ProductImage { ProId = "KB009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923106/Products/Keyboard/zxw6z7w9hekhjjvv5nfp.webp" },
            new ProductImage { ProId = "MS001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923837/Products/Mouse/ogckqbmnbhndhsijyvgb.webp" },
            new ProductImage { ProId = "MS001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923851/Products/Mouse/mh2dzld2pvh4yewlbsgv.webp" },
            new ProductImage { ProId = "MS001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923860/Products/Mouse/g7sfyjiwemq5jsfrrsdx.webp" },
            new ProductImage { ProId = "MS001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923876/Products/Mouse/gbohtzemnyar5ltrzumq.webp" },
            new ProductImage { ProId = "MS002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923887/Products/Mouse/pimqmbyyg0eaja5yzdbo.webp" },
            new ProductImage { ProId = "MS002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923899/Products/Mouse/i3q1wz6vikgfjishd8ox.webp" },
            new ProductImage { ProId = "MS002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923911/Products/Mouse/pvfkuh0h1h6qcuy4npwo.webp" },
            new ProductImage { ProId = "MS002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923925/Products/Mouse/tiikqco09qpqbst0jxsm.webp" },
            new ProductImage { ProId = "MS004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717923993/Products/Mouse/wbddsx39yxnxxecadtla.webp" },
            new ProductImage { ProId = "MS004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924011/Products/Mouse/mq6wq526xtabssxcejyl.webp" },
            new ProductImage { ProId = "MS004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924026/Products/Mouse/mm2wufq59qpsj3fbl0fx.webp" },
            new ProductImage { ProId = "MS004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924034/Products/Mouse/z7onxpngxtjo4ogrsap1.webp" },
            new ProductImage { ProId = "MS005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924051/Products/Mouse/y91dlwdum1htpziwhnvr.webp" },
            new ProductImage { ProId = "MS005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924064/Products/Mouse/gf2cbbab8q2wclpbmlid.webp" },
            new ProductImage { ProId = "MS005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924075/Products/Mouse/zsa8kir9nkrd6ev5uogq.webp" },
            new ProductImage { ProId = "MS005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924131/Products/Mouse/ikhwvha7scorksgmss7q.webp" },
            new ProductImage { ProId = "MS006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924146/Products/Mouse/zffgimwmesrf9rhbleqt.webp" },
            new ProductImage { ProId = "MS006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924156/Products/Mouse/wt008mjitxxrzbwaaebw.webp" },
            new ProductImage { ProId = "MS006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924169/Products/Mouse/zxkzsw91dzxpusmz6k0b.webp" },
            new ProductImage { ProId = "MS006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924176/Products/Mouse/rns1sxypzutuyoff8eow.webp" },
            new ProductImage { ProId = "MS007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924194/Products/Mouse/xrnh5u1udlntotulqr6p.webp" },
            new ProductImage { ProId = "MS007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924203/Products/Mouse/tla89xszkqvpja9pxwgi.webp" },
            new ProductImage { ProId = "MS007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924223/Products/Mouse/tv49ctvl2scvnvyjxmhl.webp" },
            new ProductImage { ProId = "MS007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924236/Products/Mouse/med8n7itoibqiormxkxn.webp" },
            new ProductImage { ProId = "MS008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924256/Products/Mouse/cwr7fjk480xhzeeap4bv.webp" },
            new ProductImage { ProId = "MS008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924263/Products/Mouse/foctdwx0miheczdu7kzm.webp" },
            new ProductImage { ProId = "MS008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924277/Products/Mouse/dmk3qjw55ncbastfqnus.webp" },
            new ProductImage { ProId = "MS008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924287/Products/Mouse/lb5o5ex8gmfqtcd9xmcc.webp" },
            new ProductImage { ProId = "MS009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924300/Products/Mouse/zfozaapj1y5ozxprpiyo.webp" },
            new ProductImage { ProId = "MS009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924310/Products/Mouse/ootlyereeqrh7vcho1ym.webp" },
            new ProductImage { ProId = "MS009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924322/Products/Mouse/ys5wifkm7gd0zgvowg5e.webp" },
            new ProductImage { ProId = "MS009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924332/Products/Mouse/pehzrwnfhmb5ktqkm6o1.webp" },
            new ProductImage { ProId = "MS010", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924351/Products/Mouse/jluq7rg1x8lw2fco8vmo.webp" },
            new ProductImage { ProId = "MS010", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924359/Products/Mouse/te0ozggoxkkp4kd2las7.webp" },
            new ProductImage { ProId = "MS010", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924375/Products/Mouse/h1jyr5zqngosupa47yif.webp" },
            new ProductImage { ProId = "MS010", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924384/Products/Mouse/kmboz2k2aw48j7jnhjj1.webp" },
            new ProductImage { ProId = "MS011", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924403/Products/Mouse/vwmmkui6y0zbx4t17yaz.webp" },
            new ProductImage { ProId = "MS011", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924411/Products/Mouse/xem9xiuodspxjshrqqid.webp" },
            new ProductImage { ProId = "MS011", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924423/Products/Mouse/jexpjtwjr5rdjjacdkmb.webp" },
            new ProductImage { ProId = "MS011", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924429/Products/Mouse/ncxopaaxhiwebpfnxf0e.webp" },
            new ProductImage { ProId = "MS012", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924446/Products/Mouse/almreanydefhqs1hr7n6.webp" },
            new ProductImage { ProId = "MS012", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924453/Products/Mouse/zh23cddgcjefo1pstkdu.webp" },
            new ProductImage { ProId = "MS012", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924468/Products/Mouse/s8wkirzpnvt6ssq9pruh.webp" },
            new ProductImage { ProId = "MS012", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924475/Products/Mouse/t9kq5jdpvpdcaizjmks4.webp" },
            new ProductImage { ProId = "MS013", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924488/Products/Mouse/hxsxgi5rziw4zcfnzofl.webp" },
            new ProductImage { ProId = "MS013", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924502/Products/Mouse/mkitwfich6awxyamu43q.webp" },
            new ProductImage { ProId = "MS013", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924512/Products/Mouse/ygoxorhkpuqdtpewrtmb.webp" },
            new ProductImage { ProId = "MS013", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924527/Products/Mouse/ma1j6q5mz2mvlwbgvhlf.webp" },
            new ProductImage { ProId = "MS014", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924568/Products/Mouse/hqulprif1jqffz7ruek1.webp" },
            new ProductImage { ProId = "MS014", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924579/Products/Mouse/fywv0tdywb8dvxejlv7x.webp" },
            new ProductImage { ProId = "MS014", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924584/Products/Mouse/t7pecfc4yujihe7udikn.webp" },
            new ProductImage { ProId = "MS015", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924602/Products/Mouse/iooa4ix4h5zvqd55ir8k.jpg" },
            new ProductImage { ProId = "MS015", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924634/Products/Mouse/ghjyccnutleag4yh81ku.jpg" },
            new ProductImage { ProId = "MS015", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924641/Products/Mouse/gxgwx3ehntub5urxmrlu.jpg" },
            new ProductImage { ProId = "MS015", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924653/Products/Mouse/mdrw5tnbdy5nad8p71dc.jpg" },
            new ProductImage { ProId = "MS015", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717924663/Products/Mouse/dmkpoywae6zhllbuwqpv.jpg" },
            new ProductImage { ProId = "HP001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929167/Products/Headphone/d2gelzkvqwtxjrk2k78e.webp" },
            new ProductImage { ProId = "HP001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929180/Products/Headphone/ylrizddrkbabzdxf3vij.webp" },
            new ProductImage { ProId = "HP001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929190/Products/Headphone/v8kuyod45bwz4ojur0rp.webp" },
            new ProductImage { ProId = "HP001", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929205/Products/Headphone/usmn9qzwkskaqcwsohwe.webp" },
            new ProductImage { ProId = "HP002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929217/Products/Headphone/jhd6bvenplr1wsoavd7o.webp" },
            new ProductImage { ProId = "HP002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929229/Products/Headphone/hvruppntf0xlwoe91xdn.webp" },
            new ProductImage { ProId = "HP002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929246/Products/Headphone/cvevbk5s7tqdpbn6jndt.webp" },
            new ProductImage { ProId = "HP002", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929258/Products/Headphone/rb5c77trt3nuscycbwpc.webp" },
            new ProductImage { ProId = "HP003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929268/Products/Headphone/wzgprpn1n2suyagytpjc.webp" },
            new ProductImage { ProId = "HP003", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929281/Products/Headphone/yh3kt6fdc5ixwmjhmqw7.webp" },
            new ProductImage { ProId = "HP004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929290/Products/Headphone/zwwd85eqpljkmzlk8zqq.webp" },
            new ProductImage { ProId = "HP004", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929303/Products/Headphone/okfcvvoyuj2r2ql3higr.webp" },
            new ProductImage { ProId = "HP005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929314/Products/Headphone/mlkr3brgphruywuux571.webp" },
            new ProductImage { ProId = "HP005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929325/Products/Headphone/koh6ge2ihunt03ifbwvw.webp" },
            new ProductImage { ProId = "HP005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929339/Products/Headphone/kmozr0qh55wxvrgd3gk2.webp" },
            new ProductImage { ProId = "HP005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929350/Products/Headphone/jqpmvtibhypgidqiqmui.webp" },
            new ProductImage { ProId = "HP005", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929358/Products/Headphone/zhnviguafglskv68alrw.webp" },
            new ProductImage { ProId = "HP006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929419/Products/Headphone/ntgk0awspf8vrph35w56.webp" },
            new ProductImage { ProId = "HP006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929429/Products/Headphone/vygwsbukcgvpby15jgcf.webp" },
            new ProductImage { ProId = "HP006", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929440/Products/Headphone/aievxm2awg4moqbb9iid.webp" },
            new ProductImage { ProId = "HP007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929456/Products/Headphone/mgvi17fbjcpwy7k8axho.webp" },
            new ProductImage { ProId = "HP007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929465/Products/Headphone/oceq8tiyebyqrsqgl2us.webp" },
            new ProductImage { ProId = "HP007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929476/Products/Headphone/qzppjvjq8xltbq4hptdy.webp" },
            new ProductImage { ProId = "HP007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929490/Products/Headphone/aps2cmb3lcbswikwzuic.webp" },
            new ProductImage { ProId = "HP007", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929502/Products/Headphone/pebtjnaxetedndajonf3.webp" },
            new ProductImage { ProId = "HP008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929517/Products/Headphone/rpzpeyqyfmepb4nj74ko.webp" },
            new ProductImage { ProId = "HP008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929531/Products/Headphone/kketsifot5lqj77o2q2i.webp" },
            new ProductImage { ProId = "HP008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929544/Products/Headphone/c3ag1b8yrbqhnaekmedc.webp" },
            new ProductImage { ProId = "HP008", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1717929553/Products/Headphone/ntjunuswcydjaduutpv3.webp" },
            new ProductImage { ProId = "KB010", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1719742208/Test/qquceqblumeg6s0exkxv.png" },
            new ProductImage { ProId = "HP009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1721023740/Products/fliogmpvcubpk57q87jb.png" },
            new ProductImage { ProId = "HP009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1721023742/Products/vdpyqibbrrn0hq452xsi.png" },
            new ProductImage { ProId = "HP009", ProImg = "https://res.cloudinary.com/dklkzeill/image/upload/v1721023746/Products/vov6hn3g8wnb9kzpoptt.png" }
        );
        }
    }
}
