using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace BusinessObject.Migrations.Product
{
    /// <inheritdoc />
    public partial class InitDb : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Brands",
                columns: table => new
                {
                    BrandId = table.Column<int>(type: "int", nullable: false),
                    BrandName = table.Column<string>(type: "varchar(50)", maxLength: 50, nullable: false),
                    BrandLogo = table.Column<string>(type: "varchar(250)", maxLength: 250, nullable: false),
                    IsAvailable = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Brands", x => x.BrandId);
                });

            migrationBuilder.CreateTable(
                name: "Categorys",
                columns: table => new
                {
                    CateId = table.Column<int>(type: "int", nullable: false),
                    CateName = table.Column<string>(type: "varchar(50)", maxLength: 50, nullable: false),
                    Keyword = table.Column<string>(type: "varchar(2)", maxLength: 2, nullable: false),
                    IsAvailable = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Categorys", x => x.CateId);
                });

            migrationBuilder.CreateTable(
                name: "Products",
                columns: table => new
                {
                    ProId = table.Column<string>(type: "varchar(10)", maxLength: 10, nullable: false),
                    CateId = table.Column<int>(type: "int", nullable: false),
                    BrandId = table.Column<int>(type: "int", nullable: false),
                    ProName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    ProQuan = table.Column<int>(type: "int", nullable: false),
                    ProPrice = table.Column<double>(type: "float", nullable: false),
                    ProDes = table.Column<string>(type: "text", nullable: false),
                    Discount = table.Column<int>(type: "int", nullable: false),
                    IsAvailable = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Products", x => x.ProId);
                    table.ForeignKey(
                        name: "FK_Products_Brands_BrandId",
                        column: x => x.BrandId,
                        principalTable: "Brands",
                        principalColumn: "BrandId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Products_Categorys_CateId",
                        column: x => x.CateId,
                        principalTable: "Categorys",
                        principalColumn: "CateId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ProductAttributes",
                columns: table => new
                {
                    ProId = table.Column<string>(type: "varchar(10)", maxLength: 10, nullable: false),
                    Feature = table.Column<string>(type: "varchar(50)", maxLength: 50, nullable: false),
                    Description = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProductAttributes", x => new { x.ProId, x.Feature });
                    table.ForeignKey(
                        name: "FK_ProductAttributes_Products_ProId",
                        column: x => x.ProId,
                        principalTable: "Products",
                        principalColumn: "ProId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ProductImages",
                columns: table => new
                {
                    ProId = table.Column<string>(type: "varchar(10)", maxLength: 10, nullable: false),
                    ProImg = table.Column<string>(type: "varchar(255)", maxLength: 255, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProductImages", x => new { x.ProId, x.ProImg });
                    table.ForeignKey(
                        name: "FK_ProductImages_Products_ProId",
                        column: x => x.ProId,
                        principalTable: "Products",
                        principalColumn: "ProId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Brands",
                columns: new[] { "BrandId", "BrandLogo", "BrandName", "IsAvailable" },
                values: new object[,]
                {
                    { 1, "https://res.cloudinary.com/dklkzeill/image/upload/v1717914957/Brands/dkrlpjps52vsacomynik.png", "Asus", false },
                    { 2, "https://res.cloudinary.com/dklkzeill/image/upload/v1717914988/Brands/ocvp75lvpkobdl7tsluu.png", "Logitech", true },
                    { 3, "https://res.cloudinary.com/dklkzeill/image/upload/v1717915043/Brands/u15iyz2vnl9szxsiuee0.png", "Corsair", true },
                    { 4, "https://res.cloudinary.com/dklkzeill/image/upload/v1717915068/Brands/mkm8jxdozqvkyp6unk0k.jpg", "DareU", true },
                    { 5, "https://res.cloudinary.com/dklkzeill/image/upload/v1717915086/Brands/y8ejiik9cch4ooenuv5b.webp", "Akko", true },
                    { 6, "https://res.cloudinary.com/dklkzeill/image/upload/v1717915101/Brands/fgxosmijxov7wpfm1c8x.png", "Razer", true },
                    { 7, "https://res.cloudinary.com/dklkzeill/image/upload/v1717915116/Brands/i1mkyisiddlvx0tlj41n.jpg", "Steelseries", true },
                    { 8, "https://res.cloudinary.com/dklkzeill/image/upload/v1717915138/Brands/rzed9esfc4alzf2u1rjb.png", "HyperX", true }
                });

            migrationBuilder.InsertData(
                table: "Categorys",
                columns: new[] { "CateId", "CateName", "IsAvailable", "Keyword" },
                values: new object[,]
                {
                    { 1, "Keyboard", true, "KB" },
                    { 2, "Mouse", true, "MS" },
                    { 3, "Headphone", true, "HP" },
                    { 4, "Gaming Chairs", true, "GC" },
                    { 5, "Controller", true, "CT" }
                });

            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "ProId", "BrandId", "CateId", "Discount", "IsAvailable", "ProDes", "ProName", "ProPrice", "ProQuan" },
                values: new object[,]
                {
                    { "CT001", 6, 5, 20, true, "Razer Raiju Ultimate is one of the products that supports gamers from one of the world''s leading gaming gear manufacturers in addition to the product lines of  mechanical keyboards , gaming mice and gaming headsets. Designed specifically for gamers: With a height and shape for your thumb to adapt to, and a choice of different D-pad layouts, use the Razer Raiju Ultimate to choose the one that''s most comfortable for your hand. . A handle with a reasonable layout will help you hold the key to avoid pressing it", "Razer Raiju Ultimate1", 250.0, 15 },
                    { "CT002", 4, 5, 0, true, "DareU H101X Wireless Pink', 10, 40, N'For console gamers, one of the indispensable and widely used gaming accessories today is the game controller. And to bring a breath of fresh air in this product segment, DareU has launched a product from its own production line with a model called DareU H101X Wireless Pink . Let''s learn more about this product with GEARVN! Gentle and feminine design Complete with a symmetrical - ergonomic design, DareU H101X Wireless Pink provides comfort when using a gaming controller , suitable and suitable for all hand shapes. The grip and grip area of ??the DareU H101X Wireless Pink is smooth to create a comfortable feeling when used for long periods of time. Coming to the stylish pink version, DareU H101X Wireless Pink brings gentleness and prominence to female gamers or \"strong\" entertainment corners, through extremely personal details and button icons.", "DareU H101X Wireless Pink", 40.0, 10 },
                    { "CT003", 4, 5, 20, true, "DareU H1056X Wireless ', 10, 70, N'For console gamers, one of the indispensable and widely used gaming accessories today is the game controller. And to bring a breath of fresh air in this product segment, DareU has launched a product from its own production line with a model called DareU H101X Wireless Black . Let''s learn more about this product with GEARSHOP!", "DareU H1056X Wireless", 70.0, 10 },
                    { "CT004", 1, 5, 0, true, "For console gaming setups, game controllers are indispensable devices for gamers. Always among the top gaming consoles, Xbox from Microsoft is always the top choice for all gamers, especially the controller product line. And here GEARVN will introduce to you the latest Asus ROG Raikiri Pro with the greatest improvements.", "Asus ROG Raikiri Pro", 180.0, 5 },
                    { "GC001", 3, 4, 20, true, "Corsair TC100 Leatherette Black CF-9010050-WW gaming chair line has a unique design that adds inspiration when playing games and working. At the same time, it is made from high-quality materials to bring a feeling of comfort all day long.", "Corsair TC100 Leatherette Chair", 200.0, 5 },
                    { "GC002", 1, 4, 0, true, "Crafted for comfort. The ROG Chariot Core gaming chair evokes the style and feel of a high-end racing car. With a high-density foam headrest, memory foam lumbar support, breathable PU leather seat, 4D adjustable armrests, lockable tilt mechanism and highly durable components, the Chariot Core giving you safe, comfortable style - and allowing you to express your own personality in any gaming arena.", "ASUS ROG Chariot Core Chair", 450.0, 5 },
                    { "GC003", 6, 4, 20, true, "If you are a gamer or regular computer user, the name gaming chair is no longer strange to you, right? To be able to mention one of the top names in the gaming chair industry, Razer will always be named on our list. The brand with the three beams logo has launched a new groundbreaking gaming chair called Razer ISKUR X. Let's learn more details about this product with GEARVN right here!", "Razer ISKUR X Chair", 300.0, 0 },
                    { "GC004", 3, 4, 0, true, "Not only does it possess an aggressive design through meticulously crafted angular lines, the Corsair TC200 with its luxurious Light Gray/White color tone and Leatherette leather material will highlight every corner of the camera.", "Corsair TC200 Leatherette", 200.0, 5 },
                    { "HP001", 1, 3, 20, true, "The Asus ROG Delta S Core headset is the lightest gaming headset model currently in the Asus Delta series with a weight of only 270 grams. Designed for unmatched performance and comfort, the Delta S Core features convenient and modern D-shaped ear cups. It fits the ear shape of most users perfectly, reducing unwanted contact area by up to 20% for a better fit and comfort. Exclusive 50mm ASUS Essence drivers with virtual 7.1 surround sound and boom microphone to deliver the ultimate gaming experience certified by Discord and TeamSpeak.", "Asus ROG Delta S Core", 90.0, 0 },
                    { "HP002", 1, 3, 0, true, "Always known for its extremely high-quality products, TUF Gaming also scores points in the eyes of users thanks to its affordable prices. From monitors, laptops to VGA, TUF Gaming always tries to bring the best experience and meet all the needs of the most demanding users. And now, the 'child' from ASUS will enter the equally pleasant market, which is headphones with the ASUS TUF Gaming H1. Let's learn more about the product with GEARVN right here!", "ASUS TUF GAMING H1", 50.0, 10 },
                    { "HP003", 2, 3, 20, false, "Logitech G733 LIGHTSPEED Wireless White line of computer headsets are designed to bring comfort to gamers. This wireless headset is equipped with the stereophonic sound, audio filters and advanced lighting features you need to see, speak and play in style like never before. Eye-catching design, super light weight. Designed in the shape of an Over-ear headphone with a weight of only 278 grams, a little more than half a pound (250g). It is very lightweight and the elastic straps are designed to reduce and distribute weight.", "Logitech G733 LIGHTSPEED", 120.0, 20 },
                    { "HP004", 2, 3, 0, true, "Loud and clear sound: The over-the-ear headset has a built-in 6mm enhanced large mic to ensure your teammates can hear you. The mic boom can be folded away to mute when you don't want your voice to be heard. DTS HEADPHONE:X 2.0 technology: New generation DTS Headphone:X 2.0 surround sound makes Logitech's computer headset more unique, using Logitech's G HUB software, allowing you to hear enemies hiding behind, possible signals Special features and immersive environments - all around you. Experience 3D audio that goes beyond 7.1 channels to make you feel like you're in the action.", "Logitech G431 Headset", 70.0, 50 },
                    { "HP005", 8, 3, 20, true, "HyperX Cloud III Wireless headset is the new gaming headset from Hyper. The Cloud Core series always leaves a mark in the hearts of users because of its excellent sound quality, players will be immersed in clear, vivid sounds. HyperX Cloud Core Wireless can be said to be one of the most worthy wireless headsets for gamers at the moment. Beautiful HyperX Cloud Core design: The HyperX Cloud Core computer headset has a simple earcup design with the signature HyperX logo right on the ear cup. The combination of black and red tones creates an extremely harmonious, luxurious and clean overall.", "HyperX Cloud III Headset", 100.0, 54 },
                    { "HP006", 6, 3, 20, true, "Black Shark V2 Pro, the latest line of gaming headphones from Razer, is integrated with many modern technologies to bring players vivid, powerful sound quality. It doesn't stop there, thanks to the super soft Flowknit cushioning, it will bring a comfortable and airy feeling when used all day long.", "Razer Shark V2 Pro Black", 220.0, 2 },
                    { "HP007", 7, 3, 0, true, "Steelseries is known as a manufacturer of Gaming Gear devices that possess impressive performance and luxurious design. That is shown through the latest product line from the company, Arctis 7 Plus is a line of bluetooth gaming headsets equipped with many modern features, easily compatible with all systems from USB-C to PS5.", "Steelseries Arctis 7 Plus", 175.0, 6 },
                    { "HP008", 7, 3, 0, true, "Computer headset with high-precision audio drivers inherited from Arctis Pro, fine-tuned for maximum accuracy for the most intense gaming sessions.", "Steelseries Arctis Prime", 120.0, 3 },
                    { "HP009", 3, 3, 0, true, "edadwa", "Test01", 100.0, 0 },
                    { "KB001", 1, 1, 20, true, "Detailed review of the ASUS ROG Strix Flare II Nx Blue Switch mechanical keyboard. Not only outstanding in PC component product lines, ASUS is also known as one of the brands that specializes in bringing extremely high-class gaming gear peripherals in terms of design and performance, from headset lines. gaming, multi-connected computer mice from wired to wireless and even gaming keyboards.", "ASUS ROG Strix Flare II", 160.0, 34 },
                    { "KB002", 2, 1, 0, true, "Logitech GX Switch. Logitech's exclusive GX switch version delivers high performance and long-lasting durability over time. One of the logitech g pro combo mechanical keyboard product lines has an integrated hot swap feature that allows you to replace another switch to innovate the experience during use. The vast Logitech G Hub ecosystem provides you with not only the ability to customize each key RGB LED effect on the Logitech G Pro Gaming computer mice, headphones, etc. in this ecosystem. In addition, you can also use this software to assign extremely convenient macro tasks.", "Logitech G Pro X", 140.0, 2 },
                    { "KB003", 3, 1, 0, true, "Detailed review of the Corsair K60 Pro Red Led gaming keyboard. Beauty and roughness: The cheap mechanical keyboard Corsair K60 Pro Red Led has a minimalist design, combining many angular lines to create an extremely elegant looking keyboard. Viola Switch comes from Cherry: Corsair has equipped the Corsair K60 Pro Red Led with a new type of switch that no brand has used before, which is Cherry Viola. This type of switch provides fast, linear key press speed (almost like Cherry Red), simple, durable switch structure and key travel is still 4mm and the active point is 2mm. Overall, this will be a switch that is very easy to get used to and suitable for gaming needs.", "Corsair K60 Pro Red", 130.0, 43 },
                    { "KB004", 4, 1, 20, true, "Detailed review of DareU EK520 Optical mechanical keyboard. The DareU EK520 keyboard is manufactured by DareU, a company specializing in providing peripheral devices for gamers and office workers. Products from Dareu are of high quality and affordable for consumers. Good material, cheap price: The DareU EK520 keyboard is designed with a frame made from sturdy, durable, and smooth material. Along with the keycaps made from high-quality plastic, it ensures a long life for the device, without the keys fading after a long time.", "DareU EK520", 35.0, 50 },
                    { "KB005", 5, 1, 0, true, "Detailed review of the AKKO 3098 RF Dracula Castle keyboard. AKKO 3098 RF Dracula Castle is a cheap mechanical keyboard line with a color scheme inspired by Count Dracula, giving players a lot of creative inspiration and excitement when playing recreational games. In particular, thanks to the Fullsize Layout and exclusive AKKO V3 switches, this promises to be the computer keyboard line you are looking for!", "AKKO 3098 RF Dracula", 70.0, 30 },
                    { "KB006", 6, 1, 0, true, "The world's first and most iconic Razer Blackwidow V3 Pro mechanical keyboard makes a landmark development. Enter a new wireless meta with the Razer BlackWidow V3 Pro—with 3 connection modes that deliver unparalleled versatility and a satisfying gaming experience including best-in-class switches and full-height keys. Razer Blackwidow V3 Pro Green Switch - a mechanical bluetooth keyboard equipped with our most advanced wireless technology for low-latency gaming and ultra-responsive input—delivered via an optimized data protocol optimized, ultra-fast radio frequency and seamless frequency switching in the noisiest, data-saturated environments.", "Razer Blackwidow V3 Pro", 230.0, 7 },
                    { "KB007", 7, 1, 20, true, "Apex 3 series mechanical keyboards are certified to be water and dust resistant according to IP32 standards (IP32 is an industry standard for water and dust resistance). Waterproof and dustproof keeps your keyboard clean and has a long life. You don't have to worry about accidentally getting your keyboard wet. With the IP32 standard, dirt and debris will have a harder time penetrating the keyboard, making the internal components safe for long-term use.", "Steelseries Apex 3", 70.0, 15 },
                    { "KB008", 6, 1, 0, true, "Razer DeathStalker V2 Pro TKL possesses a compact, thin and extremely luxurious design. In the segment, the TKL gaming keyboard DeathStalker V2 Pro TK will be one of the choices you should not miss.", "Razer DeathStalker V2", 120.0, 6 },
                    { "KB009", 5, 1, 0, true, "AKKO 3098S World Tour London is a product line that continues the success of the 'World Tour Tokyo' series with impressive and unique color combinations. Along with performance upgrades, GEARVN is confident that the AKKO 3098S World Tour London will be a mechanical keyboard line that you should not miss.", "AKKO 3098S World Tour London", 120.0, 6 },
                    { "KB010", 3, 1, 1, true, "dadaw", "Test", 100.0, 10 },
                    { "MS001", 1, 2, 20, true, "ASUS - The brand is extremely famous for its technology products, from laptops to computer components. And when it comes to gaming gear, ASUS still owns a high-end gaming mouse product line called ASUS ROG Harpe Ace. Let's welcome the latest version of the product lineup with the ASUS ROG Harpe Ace Aim Lab Edition model. Join GEARVN to learn more about this mouse!", "Asus ROG Harpe Ace", 115.0, 7 },
                    { "MS002", 1, 2, 0, true, "ASUS - The brand is extremely famous for its technology products, from laptops to computer components. And when it comes to gaming gear, ASUS still owns a high-end gaming mouse product line called Asus ROG Chakram X. Let's welcome the latest version of the product lineup with the Asus ROG Chakram X. Beautiful with Aura Sync RGB lighting. The ROG logo on Asus ROG Chakram X adorns the mouse, affirming the name of the famous gaming laptop brand. Combined with the brilliant ARGB effects on Aura Sync RGB, this will be a great decoration for PC systems and entertainment and work corners.", "Asus ROG Chakram X", 130.0, 43 },
                    { "MS004", 1, 2, 0, true, "Accurate and high performance. Asus collaborated with professional gamers in designing ROG Strix Impact II, delivering an ambidextrous ergonomic design optimized for performance play and comfortable grip, with a weight of just 79g. The 6,200 dpi sensor tracks at up to 220 ips and with a 1000 Hz polling rate, so you're guaranteed high accuracy, quick response and precise control - and all without a hint of lag. Impact II even includes five programmable buttons, allowing you to customize controls for your game or play style.", "Asus ROG Strix Impact II", 50.0, 7 },
                    { "MS005", 2, 2, 20, true, "Logitech G502 X PLUS Mouse is the latest product of the popular G502 series. Redesigned and enhanced with modern gaming technology, including the first hybrid optical-mechanical Lightforce switch, Wireless Lightspeed, LIGHT SYNC RGB and Hero 25K optical sensor, the rugged Logitech G502 X PLUS is one of the most worth buying gaming gear for gamers in the near future.", "Logitech G502 X", 150.0, 6 },
                    { "MS006", 2, 2, 0, true, "Logitech G703 HERO Lightspeed Wireless Mouse. Logitech G703 is one of the computer mouse lines that possesses an ergonomic design that hugs the palm of the hand to support each mouse movement more firmly. G703 is one of the latest Logitech wireless mouse product lines to join the game with the new generation 16K HERO sensor. Logitech's most advanced sensor to date, with 1:1 tracking, 400+ IPS, and 100-16,000 maximum DPI sensitivity — plus smoothing, filtering, and acceleration. Logitech G703 is one of the few wireless gaming computer mice with a comfortable design and light weight, with a rubber handle to help increase mouse movement. In addition, during use, users can customize the weight of the mouse with the 10g option to help you be more flexible in use.", "Logitech G703 HERO", 75.0, 4 },
                    { "MS007", 6, 2, 0, true, "Detailed review of the Razer Cobra mouse. The Razer Cobra line of gaming mice has a symmetrical design that makes mouse movements more secure. At the same time, equipped with up to 6 buttons intelligently arranged along the mouse body to help make operations more effective. This promises to be one of the gaming computer mouse lines worth owning from Razer!", "Razer Cobra", 50.0, 9 },
                    { "MS008", 6, 2, 20, true, "Victory takes on a new shape with the Razer DeathAdder V3 Pro. Refined and reforged with the aid of top esports pros, its iconic ergonomic form is now more than 25% lighter than its predecessor, backed by a set of cutting-edge upgrades to push the limits of competitive play. Razer DeathAdder V3 Pro's ergonomic design and wireless connection give you a comfortable feeling when used for long periods of time. Perfectly suited for palm grip, and also works well with fingertip swipes.", "Razer DeathAdder V3", 140.0, 9 },
                    { "MS009", 7, 2, 0, true, "Detailed review of the Steelseries Rival 5 mouse product. The Steelseries Rival 5 product is a gaming computer mouse with high precision and flexibility. Players can dominate any game with 9 customizable buttons and lightning-fast toggles. Freely program 9 custom buttons. Players have the right to adjust important keys for convenience in use. The side of the mouse comes with 5 buttons designed for thumb use. Increase the speed of performing many operations so players can have great game experience moments.", "Steelseries Rival 5", 35.0, 7 },
                    { "MS010", 4, 2, 20, true, "DareU EM908 RGB has a compact, beautiful design. One of the gaming mouse lines that possesses a palm-sized appearance and size with an ergonomic design that is convenient for the user. Brings a sense of comfort to gamers and users who have to work for long periods of time without feeling tired when using DAREU EM908 for long periods of time. In addition, to synchronize with the computer system DareU has equipped the EM908 mouse line with a beautiful RGB LED strip of 16.7 million colors around the edge of the mouse.", "Dare-U EM908 RGB", 25.0, 7 },
                    { "MS011", 5, 2, 0, true, "Akko Hamster Wireless is designed to be small, more suitable for women's hands, but if you are used to holding claw-grip or Fingertip mice, you will definitely be satisfied with the 'fat' body of these hamsters. This hamster. Akko Hamster is finished with pre-colored ABS plastic, not painted on the surface, so the color will definitely last over time. Combined with a set of extremely chill pastel colors, it will definitely please the ladies, and even the guys with gentle, peaceful personalities.", "Akko Hamster Plus", 20.0, 6 },
                    { "MS012", 3, 2, 0, true, "Detailed review of Corsair M65 RGB ULTRA Black mouse. Corsair, a brand that is extremely popular with gamers with its PC components, streaming accessories,... Especially gaming gear products, are always perfected with a bold gaming design and special features. Those will be the strengths that Corsair M65 RGB ULTRA Black will possess. So let's see with GEARVN what else the gaming mouse from Corsair can bring to gamers!", "Corsair M65 RGB", 65.0, 7 },
                    { "MS013", 8, 2, 0, true, "Detailed review of the HP HYPERX Pulsefire Haste mouse. HyperX Pulsefire Haste 2 lines of gaming computer mice have a symmetrical design that hugs the palm of the hand, making all operations more secure. Integrating many modern technologies from HyperX, this promises to be one of the gaming mouse lines that offers the outstanding physical control you are looking for. Ergonomic design, hugs the palm. Possessing an ergonomic mouse design with a symmetrical grip form that hugs the entire palm of the hand, making each mouse move more secure and reducing pressure on the wrist when used for long periods of time. HYPERX Pulsefire Haste 2 is finished with black as the main color tone, the rounded details are meticulously machined to create an extremely beautiful overall. It is promised that when placed next to a mechanical keyboard, a gaming computer headset will create an extremely high-quality, beautiful gaming space.", "HYPERX Pulsefire Haste II", 60.0, 4 },
                    { "MS014", 1, 2, 20, true, "ASUS ROG Keris is equipped with a specially tuned 16,000 dpi sensor. It features ROG's exclusive push-fit switch sockets and ROG Micro Switches, along with left and right PBT polymer buttons, Asus ROG Omni mouse feet, ROG Paracord lighting, and Aura Sync RGB.", "ASUS ROG Keris", 65.0, 4 },
                    { "MS015", 1, 2, 20, true, "Asus Gladius II is designed for people who feeling sad in love, with powerful design, this mouse can make you feel good, never feel sad, like when you eat coconut, drink watermelon, take a bath in beach and swim in bathroom.", "Asus Gladius II", 70.0, 4 }
                });

            migrationBuilder.InsertData(
                table: "ProductAttributes",
                columns: new[] { "Feature", "ProId", "Description" },
                values: new object[,]
                {
                    { "Cable length", "CT001", "3m" },
                    { "Compatible", "CT001", "PC/PS4" },
                    { "Connect", "CT001", "Bluetooth/Wired" },
                    { "Size", "CT001", "106 x 155 x 66 ( mm )" },
                    { "Software that can be used", "CT001", "Raiju application (IOS/ANDROID)" },
                    { "Switch Type", "CT001", "RAZER MECHA-TACTILE" },
                    { "Trademark", "CT001", "Razer" },
                    { "Used Time", "CT001", "11 hours (Bluetooth)" },
                    { "Weight", "CT001", "370 g" },
                    { "Compatible", "CT002", "PC, Switch, Android TV & phone" },
                    { "Connect", "CT002", "Wireless" },
                    { "Size", "CT002", "160mm x 105mm x 62mm" },
                    { "The battery", "CT002", "650mAh" },
                    { "Trademark", "CT002", "DareU" },
                    { "Weight", "CT002", "˜220g" },
                    { "Wire length", "CT002", "1.8M" },
                    { "Compatible", "CT003", "PC, Switch, Android TV & phone" },
                    { "Connect", "CT003", "Wireless" },
                    { "Size", "CT003", "160mm x 105mm x 62mm" },
                    { "The battery", "CT003", "650mAh" },
                    { "Trademark", "CT003", "DareU" },
                    { "Weight", "CT003", "˜220g" },
                    { "Wire length", "CT003", "1.8M" },
                    { "Battery life", "CT004", "Battery life up to 48 hours of use (no lights on, vibration off)" },
                    { "Connect", "CT004", "Wired / Wireless (2.4 Ghz) / Bluetooth" },
                    { "Screen", "CT004", "1.3inch with 128x40 resolution, 2 gray levels" },
                    { "Trademark", "CT004", "Asus" },
                    { "Backrest height", "GC001", "81 cm" },
                    { "Backrest width", "GC001", "33 cm" },
                    { "Chair arm height", "GC001", "45 – 52" },
                    { "Handrail type", "GC001", "2D" },
                    { "Lumbar pillow", "GC001", "Have" },
                    { "Material", "GC001", "PU leather" },
                    { "Maximum height", "GC001", "188 cm" },
                    { "Maximum load", "GC001", "120 kg" },
                    { "Minimum height", "GC001", "45 – 55 cm" },
                    { "Neck pillow", "GC001", "Have" },
                    { "Number of wheels", "GC001", "5" },
                    { "Seat width", "GC001", "54 cm" },
                    { "Trademark", "GC001", "Corsair" },
                    { "Weight", "GC001", "18.30kg" },
                    { "Wheel material", "GC001", "High quality plastic" },
                    { "Armrest", "GC002", "4D (Up/Down, Left/Right, Front/Back, Swivel)" },
                    { "Chair back height", "GC002", "85cm" },
                    { "Chair frame material", "GC002", "Metal" },
                    { "Chair size", "GC002", "134 – 142 x 73 x 73 (cm) (Height x Length x Width)" },
                    { "Material", "GC002", "High quality PU leather" },
                    { "Reclining angle", "GC002", "85° ~ 165°" },
                    { "Seat back width", "GC002", "73cm" },
                    { "Trademark", "GC002", "Asus" },
                    { "Weight", "GC002", "120kg" },
                    { "Wheel Size", "GC002", "65mm" },
                    { "Air lift layer", "GC003", "4" },
                    { "Armrest", "GC003", "2D" },
                    { "Chair cover color", "GC003", "Black, blue" },
                    { "Chair frame material", "GC003", "Metal & Plywood" },
                    { "Chair weight (kg)", "GC003", "25" },
                    { "Material", "GC003", "PVC leather" },
                    { "Maximum load (kg)", "GC003", "136" },
                    { "Reclining angle", "GC003", "90°-139°" },
                    { "Trademark", "GC003", "Razer" },
                    { "Wheel", "GC003", "Caster 6 cm" },
                    { "Connect", "HP001", "Has standard 3.5mm wire" },
                    { "Driver", "HP001", "50mm" },
                    { "Feature", "HP001", "7.1 virtual surround sound system powered by Windows Sonic" },
                    { "Headphone style", "HP001", "Over-ear" },
                    { "Impedance", "HP001", "32 Ohms" },
                    { "Model", "HP001", "Asus ROG Delta S Core" },
                    { "Sensitivity", "HP001", "-40 dB" },
                    { "Trademark", "HP001", "Asus" },
                    { "Connect", "HP002", "Has a 3.5mm cable" },
                    { "Driver size", "HP002", "40mm" },
                    { "Impedance", "HP002", "60 ohms" },
                    { "Microphone frequency", "HP002", "100Hz - 10Khz" },
                    { "Microphone sensitivity", "HP002", "-45dB" },
                    { "Response frequency", "HP002", "20Hz - 20Khz" },
                    { "Trademark", "HP002", "Asus" },
                    { "Weight", "HP002", "287 gr" },
                    { "Compatible", "HP003", "Windows 7 or later / MacOS X 10.12 or later / PlayStation 4" },
                    { "Connect", "HP003", "Wireless" },
                    { "Connection standard", "HP003", "Receiver USB type A" },
                    { "Frequency", "HP003", "20Hz - 20KHz" },
                    { "Headphone cushion material", "HP003", "Airy fabric" },
                    { "Headphone type", "HP003", "Over-ear" },
                    { "Impedance", "HP003", "1kHz 32Ohm" },
                    { "Trademark", "HP003", "Logitech" },
                    { "Compatible", "HP004", "Windows / MacOS / PlayStation 4 / Nintendo Switch / Smartphone" },
                    { "Connection standard", "HP004", "3.5mm / USB type A" },
                    { "Connection typ", "HP004", "Wired" },
                    { "Frame material", "HP004", "Alloy" },
                    { "Frequency", "HP004", "20Hz - 20KHz" },
                    { "Headphone type", "HP004", "Over-ear" },
                    { "Impedance", "HP004", "1 kHz 32 Ohm" },
                    { "Microphone", "HP004", "Can be folded when not in use" },
                    { "Trademark", "HP004", "Logitech" },
                    { "Cable Length", "HP005", "Headphone cable 1.2m, USB dongle cable 1m3" },
                    { "Connection via jack", "HP005", "3.5mm, USB" },
                    { "Diaphragm", "HP005", "53mm" },
                    { "Frame Type", "HP005", "Aluminum" },
                    { "Included accessories", "HP005", "Microphone, USB soundcard" },
                    { "Response frequency", "HP005", "10Hz-21kHz" },
                    { "Sensitivity", "HP005", "-42dBV (0dB = 1V/Pa at 1kHz)" },
                    { "Trademark", "HP005", "HyperX" },
                    { "Battery life", "HP006", "Up to 70 hours" },
                    { "Connection type", "HP006", "Type A wireless (2.4 GHz), Bluetooth 5.2" },
                    { "Drivers", "HP006", "50 mm" },
                    { "Headphone cushion material", "HP006", "Breathable foam mattress" },
                    { "Headphone type", "HP006", "Over-ear" },
                    { "Impedance", "HP006", "32 Ohms" },
                    { "Noise cancellation", "HP006", "Advanced passive noise cancellation" },
                    { "Response frequency", "HP006", "12 Hz - 28 kHz" },
                    { "Sensitivity", "HP006", "100 dBSPL/mW @ 1 kHz using HATS" },
                    { "Trademark", "HP006", "Razer" },
                    { "Weight", "HP006", "320 g" },
                    { "AURA Sync", "KB001", "AURA Sync" },
                    { "Connect", "KB001", "Wired (USB 2.0)" },
                    { "Keyboard style", "KB001", "Full size 100%" },
                    { "Led", "KB001", "Led" },
                    { "Macro keys", "KB001", "All keys are programmable" },
                    { "Trademark", "KB001", "Asus" },
                    { "Weight", "KB001", "1113g" },
                    { "Connect", "KB002", "Wired" },
                    { "Size", "KB002", "361 x 153 x 34 (mm)" },
                    { "Switch", "KB002", "Logitech GX Switch Clicky" },
                    { "Trademark", "KB002", "Logitech" },
                    { "Weight", "KB002", "1kg" },
                    { "CHERRY® VIOLA", "KB003", "ABS Doubleshot" },
                    { "Connect", "KB003", "Wired, USB 2.0 Type A" },
                    { "Led", "KB003", "RED" },
                    { "Size", "KB003", "FullSize" },
                    { "Switch", "KB003", "CHERRY VIOLA" },
                    { "Trademark", "KB003", "Corsair" },
                    { "Weight", "KB003", "Weight" },
                    { "Connect", "KB004", "USB cord" },
                    { "LED", "KB004", "Multi" },
                    { "Switch", "KB004", "Optical" },
                    { "Trademark", "KB004", "DareU" },
                    { "Connect", "KB005", "USB Type-C to Type-A (detachable cord)" },
                    { "Design", "KB005", "98 Keys" },
                    { "Size", "KB005", "382 x 134 x 40 mm" },
                    { "Switch", "KB005", "Akko switch v3 (Cream Blue Pro/ Cream Yellow Pro)" },
                    { "The battery", "KB005", "1300mah" },
                    { "Trademark", "KB005", "Akko" },
                    { "Weight", "KB005", "382 x 134 x 40 mm" },
                    { "Connect", "KB006", "USB, Bluetooth, 2.4 Ghz Wireless" },
                    { "Designs", "KB006", "Designs" },
                    { "Keycaps", "KB006", "Keycap ABS Doubleshot" },
                    { "Switch", "KB006", "Razer Mechanical Green/Yellow" },
                    { "Trademark", "KB006", "Razer" },
                    { "Connection", "KB007", "Wired keyboard" },
                    { "Keycaps material", "KB007", "ABS" },
                    { "Size", "KB007", "Length 444.7 x Width 151.62 x Height 39.69 mm" },
                    { "Switch", "KB007", "SteelSeries Whisper-Quiet Switches" },
                    { "Trademark", "KB007", "Steelseries" },
                    { "Weight", "KB007", "816 grams" },
                    { "Connect", "KB008", "Wired / Wireless (2.4 Ghz) / Bluetooth" },
                    { "LED", "KB008", "Razer Chroma™ RGB with 16.8 million colors" },
                    { "Media keys", "KB008", "Have" },
                    { "Switch", "KB008", "Razer™ Low-Profile Optical (Linear)" },
                    { "Connect", "KB009", "USB Type-C, detachable" },
                    { "LED", "KB009", "RGB background (Backlit, SMT bottom without switch) with many modes" },
                    { "Number of keys", "KB009", "98 Keys" },
                    { "Size", "KB009", "382 x 134 x 40 mm" },
                    { "Switch", "KB009", "AKKO CS Silver" },
                    { "Trademark", "KB009", "Akko" },
                    { "Weight", "KB009", "1.1kg" },
                    { "Connect", "MS001", "Wired / Bluetooth 5.1 / Wireless 2.4GHz" },
                    { "Designs", "MS001", "Symmetry" },
                    { "DPI", "MS001", "36000" },
                    { "IPS", "MS001", "650" },
                    { "Trademark", "MS001", "Asus" },
                    { "Weight", "MS001", "54G" },
                    { "Battery life", "MS002", "Up to 150h" },
                    { "Connection", "MS002", "Wired / Wireless RF 2.4GHz / Bluetooth" },
                    { "Sensitivity (DPI)", "MS002", "100 ~ 36000" },
                    { "Switch", "MS002", "70 million clicks" },
                    { "Trademark", "MS002", "Asus" },
                    { "Connect", "MS004", "USB 2.0" },
                    { "Sensor", "MS004", "Pixart3327" },
                    { "Trademark", "MS004", "Asus" },
                    { "Battery life", "MS005", "Up to 130 hours (37 hours with RGB enabled)" },
                    { "Charging port", "MS005", "USB-C" },
                    { "Connect", "MS005", "LIGHTSPEED wireless technology" },
                    { "Max speed", "MS005", "> 400 IPS" },
                    { "Maximum acceleration", "MS005", "> 40G2" },
                    { "Size", "MS005", "131.4 mm x 41.1 mm x 79.2 mm" },
                    { "Trademark", "MS005", "Logitech" },
                    { "Connect", "MS006", "Wireless" },
                    { "DPI sensitivity", "MS006", "100-16,000 maximum" },
                    { "IPS", "MS006", "400+" },
                    { "Sensor", "MS006", "16K HERO" },
                    { "Trademark", "MS006", "Logitech" },
                    { "Connection type", "MS007", "Wired" },
                    { "Sensitivity (DPI)", "MS007", "8500" },
                    { "Sensor", "MS007", "8500 DPI Optical Sensor" },
                    { "Size", "MS007", "119.6 mm / 4.71 in" },
                    { "Switch", "MS007", "Optical Mouse Switches Gen-3" },
                    { "Trademark", "MS007", "Razer" },
                    { "Connect", "MS008", "Wireless" },
                    { "DPI", "MS008", "30000" },
                    { "IPS", "MS008", "750" },
                    { "Sensor", "MS008", "Focus Pro 30K optical sensor" },
                    { "Switch", "MS008", "Optical Gen-3" },
                    { "Trademark", "MS008", "Razer" },
                    { "Connect", "MS009", "Wired" },
                    { "CPI", "MS009", "18000 CPI" },
                    { "IPS", "MS009", "400, on SteelSeries QcK surface" },
                    { "Sensor Type", "MS009", "optics" },
                    { "Size", "MS009", "128.8 x 63.35 x 28.2 (mm)" },
                    { "Switch Type", "MS009", "SteelSeries IP54 mechanical switches" },
                    { "Trademark", "MS009", "Steelseries" },
                    { "Connection", "MS010", "Wired" },
                    { "Led light", "MS010", "RGB" },
                    { "Resolution (CPI/DPI)", "MS010", "6000DPI" },
                    { "Sensor", "MS010", "BRAVO ATG4090" },
                    { "Size", "MS010", "Size" },
                    { "Trademark", "MS010", "DareU" },
                    { "Battery life", "MS011", "Up to 6 months" },
                    { "Connect", "MS011", "Wireless Wireless" },
                    { "Pixels per inch (DPI)", "MS011", "1200" },
                    { "Sensor", "MS011", "Optical" },
                    { "Trademark", "MS011", "Akko" },
                    { "Weight (gr)", "MS011", "84 (including battery)" },
                    { "Connect", "MS012", "Wired" },
                    { "DPI", "MS012", "26,000" },
                    { "Led", "MS012", "2 RGB Zones" },
                    { "Node number", "MS012", "8" },
                    { "Sensor", "MS012", "MARKSMAN 26K" },
                    { "Trademark", "MS012", "Corsair" },
                    { "Weight", "MS012", "97g" },
                    { "Connection type", "MS013", "Wired" },
                    { "Sensitivity (DPI)", "MS013", "Maximum 26,000" },
                    { "Sensor", "MS013", "HyperX 26K" },
                    { "Switch", "MS013", "up to 100 million clicks" },
                    { "Trademark", "MS013", "HyperX" },
                    { "Color", "MS015", "Black" },
                    { "Connect", "MS015", "USB 2.0" },
                    { "Connection type", "MS015", "Wired mouse" },
                    { "Resolution (CPI/DPI)", "MS015", "12000DPI" },
                    { "Switch", "MS015", "Omron" },
                    { "Trademark", "MS015", "Asus" }
                });

            migrationBuilder.InsertData(
                table: "ProductImages",
                columns: new[] { "ProId", "ProImg" },
                values: new object[,]
                {
                    { "CT001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924769/Products/Controller/qutk9vonjj39mvlwehuf.webp" },
                    { "CT001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924787/Products/Controller/fw45gyha5cgfmympydwb.webp" },
                    { "CT001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924802/Products/Controller/zyzz156z9ii0fpe1bc6q.webp" },
                    { "CT001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924811/Products/Controller/rbiyyqkrtsu7yp7fdivt.webp" },
                    { "CT002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924824/Products/Controller/b7ovbngq6xeroykeas8j.webp" },
                    { "CT002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924831/Products/Controller/fxysr9h7sn5hai0vvo3t.webp" },
                    { "CT002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924841/Products/Controller/shmkoxpgunprcqjribhq.webp" },
                    { "CT002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924846/Products/Controller/wzsg4qsbtctwfpyzfo1f.webp" },
                    { "CT002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924853/Products/Controller/zutrmelcspchnoehlm5c.webp" },
                    { "CT003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924877/Products/Controller/jxkhexqcllxwm65aurcb.webp" },
                    { "CT003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924890/Products/Controller/jdmuulygohhnhfdny6d7.png" },
                    { "CT003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924899/Products/Controller/xynykmjy1dclfd7zs9d4.png" },
                    { "CT003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924907/Products/Controller/dopzxlhlstarzoqwtn5s.png" },
                    { "CT003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924923/Products/Controller/mqzeyfkk6kzh1vom0our.png" },
                    { "CT004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924936/Products/Controller/obyvnzjnya5sakdfba4q.webp" },
                    { "CT004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924942/Products/Controller/jmgxuf8hxqjd6p5mxok2.webp" },
                    { "CT004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924959/Products/Controller/e45f1h04byzdvdzk4zzo.webp" },
                    { "CT004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924967/Products/Controller/ttpstsgf37d0i4vdlz6g.webp" },
                    { "CT004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924980/Products/Controller/olodpx1jnxwydpnliyid.webp" },
                    { "GC001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928907/Products/GamingChairs/z5hzmap76ivbbfxycj8b.webp" },
                    { "GC001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928916/Products/GamingChairs/yoybyil1wyzdfcutq3qw.webp" },
                    { "GC001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928925/Products/GamingChairs/syg6aqccmexvqsfjik3k.webp" },
                    { "GC001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928937/Products/GamingChairs/djo58phlzad9xef5jijr.webp" },
                    { "GC001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928945/Products/GamingChairs/jgsgzq1sscfwtqw6rduq.webp" },
                    { "GC002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928968/Products/GamingChairs/ppf6kqt8src7nnkdhvnz.webp" },
                    { "GC002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928975/Products/GamingChairs/x80o2ptqik8ivna21ecu.webp" },
                    { "GC002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717928987/Products/GamingChairs/mrdgigbyi3saf394gmvm.webp" },
                    { "GC003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929010/Products/GamingChairs/witqzgy8058bbnyreioi.webp" },
                    { "GC003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929025/Products/GamingChairs/p5cpb5webp9v6b64dsbr.webp" },
                    { "GC003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929034/Products/GamingChairs/mjux9kkppegkmnrmvqwx.webp" },
                    { "GC003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929044/Products/GamingChairs/wgu48tvjujgjikp2tbfn.webp" },
                    { "GC004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929057/Products/GamingChairs/dukw1cw1g3xprnpzg1z2.jpg" },
                    { "GC004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929066/Products/GamingChairs/zymtywd00sezrnj2xhh4.jpg" },
                    { "GC004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929080/Products/GamingChairs/lwqvttntlpzjic7cvyfk.jpg" },
                    { "GC004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929086/Products/GamingChairs/yn4tfqxcatqlnseutebl.jpg" },
                    { "GC004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929097/Products/GamingChairs/by0cq5p6hl253udygfgm.jpg" },
                    { "HP001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929167/Products/Headphone/d2gelzkvqwtxjrk2k78e.webp" },
                    { "HP001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929180/Products/Headphone/ylrizddrkbabzdxf3vij.webp" },
                    { "HP001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929190/Products/Headphone/v8kuyod45bwz4ojur0rp.webp" },
                    { "HP001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929205/Products/Headphone/usmn9qzwkskaqcwsohwe.webp" },
                    { "HP002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929217/Products/Headphone/jhd6bvenplr1wsoavd7o.webp" },
                    { "HP002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929229/Products/Headphone/hvruppntf0xlwoe91xdn.webp" },
                    { "HP002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929246/Products/Headphone/cvevbk5s7tqdpbn6jndt.webp" },
                    { "HP002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929258/Products/Headphone/rb5c77trt3nuscycbwpc.webp" },
                    { "HP003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929268/Products/Headphone/wzgprpn1n2suyagytpjc.webp" },
                    { "HP003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929281/Products/Headphone/yh3kt6fdc5ixwmjhmqw7.webp" },
                    { "HP004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929290/Products/Headphone/zwwd85eqpljkmzlk8zqq.webp" },
                    { "HP004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929303/Products/Headphone/okfcvvoyuj2r2ql3higr.webp" },
                    { "HP005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929314/Products/Headphone/mlkr3brgphruywuux571.webp" },
                    { "HP005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929325/Products/Headphone/koh6ge2ihunt03ifbwvw.webp" },
                    { "HP005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929339/Products/Headphone/kmozr0qh55wxvrgd3gk2.webp" },
                    { "HP005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929350/Products/Headphone/jqpmvtibhypgidqiqmui.webp" },
                    { "HP005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929358/Products/Headphone/zhnviguafglskv68alrw.webp" },
                    { "HP006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929419/Products/Headphone/ntgk0awspf8vrph35w56.webp" },
                    { "HP006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929429/Products/Headphone/vygwsbukcgvpby15jgcf.webp" },
                    { "HP006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929440/Products/Headphone/aievxm2awg4moqbb9iid.webp" },
                    { "HP007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929456/Products/Headphone/mgvi17fbjcpwy7k8axho.webp" },
                    { "HP007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929465/Products/Headphone/oceq8tiyebyqrsqgl2us.webp" },
                    { "HP007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929476/Products/Headphone/qzppjvjq8xltbq4hptdy.webp" },
                    { "HP007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929490/Products/Headphone/aps2cmb3lcbswikwzuic.webp" },
                    { "HP007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929502/Products/Headphone/pebtjnaxetedndajonf3.webp" },
                    { "HP008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929517/Products/Headphone/rpzpeyqyfmepb4nj74ko.webp" },
                    { "HP008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929531/Products/Headphone/kketsifot5lqj77o2q2i.webp" },
                    { "HP008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929544/Products/Headphone/c3ag1b8yrbqhnaekmedc.webp" },
                    { "HP008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717929553/Products/Headphone/ntjunuswcydjaduutpv3.webp" },
                    { "HP009", "https://res.cloudinary.com/dklkzeill/image/upload/v1721023740/Products/fliogmpvcubpk57q87jb.png" },
                    { "HP009", "https://res.cloudinary.com/dklkzeill/image/upload/v1721023742/Products/vdpyqibbrrn0hq452xsi.png" },
                    { "HP009", "https://res.cloudinary.com/dklkzeill/image/upload/v1721023746/Products/vov6hn3g8wnb9kzpoptt.png" },
                    { "KB001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717921892/Products/Keyboard/ywkxnxta6noyaojpmnrb.webp" },
                    { "KB001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717921996/Products/Keyboard/pyttp822qidum7t1twrr.webp" },
                    { "KB001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922015/Products/Keyboard/eui0euacsjqhpa6hrayt.webp" },
                    { "KB001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922030/Products/Keyboard/wwwocxbhmhxhy0t9rvru.jpg" },
                    { "KB002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922113/Products/Keyboard/fka2rubjgwdefmhvrdos.webp" },
                    { "KB002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922190/Products/Keyboard/e9sawikerlz0kw2lquhl.webp" },
                    { "KB002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922202/Products/Keyboard/jtqdkratpsxokxwkqjog.webp" },
                    { "KB002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922216/Products/Keyboard/zg6ioknni2duvji2puok.webp" },
                    { "KB003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922248/Products/Keyboard/hr7g8phxsb8xfybimmf7.webp" },
                    { "KB003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922280/Products/Keyboard/jurcj10bdnr2pkjymujo.webp" },
                    { "KB003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922294/Products/Keyboard/fjts0sokzhiva33he1az.webp" },
                    { "KB003", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922305/Products/Keyboard/fvu3swa7bh30m4nkkb18.webp" },
                    { "KB004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922346/Products/Keyboard/vpkbhpxqjxbxzacshoia.webp" },
                    { "KB004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922380/Products/Keyboard/u6zvauadyrerizetn59v.webp" },
                    { "KB004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922420/Products/Keyboard/hlaf0rna1tgdcnwd9wyy.webp" },
                    { "KB004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922435/Products/Keyboard/wc5rkr8zvd0bt1ih2ci7.webp" },
                    { "KB005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922464/Products/Keyboard/tweavgjpejduj0v8fwv9.webp" },
                    { "KB005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922476/Products/Keyboard/scu51fazdl6tlwosvjig.webp" },
                    { "KB005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922488/Products/Keyboard/g5qkjacnjipkpnlh1ohf.webp" },
                    { "KB005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922519/Products/Keyboard/bcithwfksf6tbk6i3ivi.webp" },
                    { "KB005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922536/Products/Keyboard/p0bydvsaj7qkbgjt3xit.webp" },
                    { "KB006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922553/Products/Keyboard/i0a6x04nx9yodis6ygwg.webp" },
                    { "KB006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922578/Products/Keyboard/zmy1x4itrnpibw83tbvm.webp" },
                    { "KB006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922603/Products/Keyboard/asbjbkvfnikenkwll156.webp" },
                    { "KB006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922620/Products/Keyboard/vtr63ngchmblratpatqs.webp" },
                    { "KB007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922632/Products/Keyboard/sbnpr0e0y3ollge0lflw.webp" },
                    { "KB007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922641/Products/Keyboard/yr2kcczh8duvnu02hofo.webp" },
                    { "KB007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922660/Products/Keyboard/wcjmdpb9kwlfbucttj7d.webp" },
                    { "KB007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922677/Products/Keyboard/mn9a5w7umabkyg1tgplt.webp" },
                    { "KB008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922962/Products/Keyboard/vyikxjpzjegxqwln7blt.webp" },
                    { "KB008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922972/Products/Keyboard/pjhqkyv1xlbanfcm4ctj.jpg" },
                    { "KB008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717922989/Products/Keyboard/iyg3amady0wjixg6istg.webp" },
                    { "KB008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923012/Products/Keyboard/wscqeir6g21ldtvuysz6.jpg" },
                    { "KB008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923032/Products/Keyboard/ib0wnl8mvmjntzufgvah.webp" },
                    { "KB009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923046/Products/Keyboard/hgbjc67rrx6pkbv1illm.webp" },
                    { "KB009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923056/Products/Keyboard/idhz1fau2x98ju9dojcm.webp" },
                    { "KB009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923071/Products/Keyboard/gaapkk1sq6km9ub8d6om.webp" },
                    { "KB009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923084/Products/Keyboard/ynecq3efezwblellfhoa.webp" },
                    { "KB009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923097/Products/Keyboard/fxczch4zcyphznps6dik.webp" },
                    { "KB009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923106/Products/Keyboard/zxw6z7w9hekhjjvv5nfp.webp" },
                    { "KB010", "https://res.cloudinary.com/dklkzeill/image/upload/v1719742208/Test/qquceqblumeg6s0exkxv.png" },
                    { "MS001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923837/Products/Mouse/ogckqbmnbhndhsijyvgb.webp" },
                    { "MS001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923851/Products/Mouse/mh2dzld2pvh4yewlbsgv.webp" },
                    { "MS001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923860/Products/Mouse/g7sfyjiwemq5jsfrrsdx.webp" },
                    { "MS001", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923876/Products/Mouse/gbohtzemnyar5ltrzumq.webp" },
                    { "MS002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923887/Products/Mouse/pimqmbyyg0eaja5yzdbo.webp" },
                    { "MS002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923899/Products/Mouse/i3q1wz6vikgfjishd8ox.webp" },
                    { "MS002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923911/Products/Mouse/pvfkuh0h1h6qcuy4npwo.webp" },
                    { "MS002", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923925/Products/Mouse/tiikqco09qpqbst0jxsm.webp" },
                    { "MS004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717923993/Products/Mouse/wbddsx39yxnxxecadtla.webp" },
                    { "MS004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924011/Products/Mouse/mq6wq526xtabssxcejyl.webp" },
                    { "MS004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924026/Products/Mouse/mm2wufq59qpsj3fbl0fx.webp" },
                    { "MS004", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924034/Products/Mouse/z7onxpngxtjo4ogrsap1.webp" },
                    { "MS005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924051/Products/Mouse/y91dlwdum1htpziwhnvr.webp" },
                    { "MS005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924064/Products/Mouse/gf2cbbab8q2wclpbmlid.webp" },
                    { "MS005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924075/Products/Mouse/zsa8kir9nkrd6ev5uogq.webp" },
                    { "MS005", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924131/Products/Mouse/ikhwvha7scorksgmss7q.webp" },
                    { "MS006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924146/Products/Mouse/zffgimwmesrf9rhbleqt.webp" },
                    { "MS006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924156/Products/Mouse/wt008mjitxxrzbwaaebw.webp" },
                    { "MS006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924169/Products/Mouse/zxkzsw91dzxpusmz6k0b.webp" },
                    { "MS006", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924176/Products/Mouse/rns1sxypzutuyoff8eow.webp" },
                    { "MS007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924194/Products/Mouse/xrnh5u1udlntotulqr6p.webp" },
                    { "MS007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924203/Products/Mouse/tla89xszkqvpja9pxwgi.webp" },
                    { "MS007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924223/Products/Mouse/tv49ctvl2scvnvyjxmhl.webp" },
                    { "MS007", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924236/Products/Mouse/med8n7itoibqiormxkxn.webp" },
                    { "MS008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924256/Products/Mouse/cwr7fjk480xhzeeap4bv.webp" },
                    { "MS008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924263/Products/Mouse/foctdwx0miheczdu7kzm.webp" },
                    { "MS008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924277/Products/Mouse/dmk3qjw55ncbastfqnus.webp" },
                    { "MS008", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924287/Products/Mouse/lb5o5ex8gmfqtcd9xmcc.webp" },
                    { "MS009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924300/Products/Mouse/zfozaapj1y5ozxprpiyo.webp" },
                    { "MS009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924310/Products/Mouse/ootlyereeqrh7vcho1ym.webp" },
                    { "MS009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924322/Products/Mouse/ys5wifkm7gd0zgvowg5e.webp" },
                    { "MS009", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924332/Products/Mouse/pehzrwnfhmb5ktqkm6o1.webp" },
                    { "MS010", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924351/Products/Mouse/jluq7rg1x8lw2fco8vmo.webp" },
                    { "MS010", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924359/Products/Mouse/te0ozggoxkkp4kd2las7.webp" },
                    { "MS010", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924375/Products/Mouse/h1jyr5zqngosupa47yif.webp" },
                    { "MS010", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924384/Products/Mouse/kmboz2k2aw48j7jnhjj1.webp" },
                    { "MS011", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924403/Products/Mouse/vwmmkui6y0zbx4t17yaz.webp" },
                    { "MS011", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924411/Products/Mouse/xem9xiuodspxjshrqqid.webp" },
                    { "MS011", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924423/Products/Mouse/jexpjtwjr5rdjjacdkmb.webp" },
                    { "MS011", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924429/Products/Mouse/ncxopaaxhiwebpfnxf0e.webp" },
                    { "MS012", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924446/Products/Mouse/almreanydefhqs1hr7n6.webp" },
                    { "MS012", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924453/Products/Mouse/zh23cddgcjefo1pstkdu.webp" },
                    { "MS012", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924468/Products/Mouse/s8wkirzpnvt6ssq9pruh.webp" },
                    { "MS012", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924475/Products/Mouse/t9kq5jdpvpdcaizjmks4.webp" },
                    { "MS013", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924488/Products/Mouse/hxsxgi5rziw4zcfnzofl.webp" },
                    { "MS013", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924502/Products/Mouse/mkitwfich6awxyamu43q.webp" },
                    { "MS013", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924512/Products/Mouse/ygoxorhkpuqdtpewrtmb.webp" },
                    { "MS013", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924527/Products/Mouse/ma1j6q5mz2mvlwbgvhlf.webp" },
                    { "MS014", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924568/Products/Mouse/hqulprif1jqffz7ruek1.webp" },
                    { "MS014", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924579/Products/Mouse/fywv0tdywb8dvxejlv7x.webp" },
                    { "MS014", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924584/Products/Mouse/t7pecfc4yujihe7udikn.webp" },
                    { "MS015", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924602/Products/Mouse/iooa4ix4h5zvqd55ir8k.jpg" },
                    { "MS015", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924634/Products/Mouse/ghjyccnutleag4yh81ku.jpg" },
                    { "MS015", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924641/Products/Mouse/gxgwx3ehntub5urxmrlu.jpg" },
                    { "MS015", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924653/Products/Mouse/mdrw5tnbdy5nad8p71dc.jpg" },
                    { "MS015", "https://res.cloudinary.com/dklkzeill/image/upload/v1717924663/Products/Mouse/dmkpoywae6zhllbuwqpv.jpg" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Products_BrandId",
                table: "Products",
                column: "BrandId");

            migrationBuilder.CreateIndex(
                name: "IX_Products_CateId",
                table: "Products",
                column: "CateId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ProductAttributes");

            migrationBuilder.DropTable(
                name: "ProductImages");

            migrationBuilder.DropTable(
                name: "Products");

            migrationBuilder.DropTable(
                name: "Brands");

            migrationBuilder.DropTable(
                name: "Categorys");
        }
    }
}
