// <auto-generated />
using System;
using BusinessObject.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations.ImportProduct
{
    [DbContext(typeof(ImportProductContext))]
    [Migration("20241003032635_InitImportProductDb")]
    partial class InitImportProductDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Models.Entity.ImportProduct", b =>
                {
                    b.Property<int>("ImportProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportProductId"));

                    b.Property<DateOnly>("DateImport")
                        .HasColumnType("date");

                    b.Property<double>("Payment")
                        .HasColumnType("float");

                    b.Property<string>("PersonInCharge")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImportProductId");

                    b.ToTable("ImportProducts");
                });

            modelBuilder.Entity("BusinessObject.Models.Entity.ReceiptProduct", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ImportProductId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("ProName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReceiptId");

                    b.HasIndex("ImportProductId");

                    b.ToTable("ReceiptProducts");
                });

            modelBuilder.Entity("BusinessObject.Models.Entity.ReceiptProduct", b =>
                {
                    b.HasOne("BusinessObject.Models.Entity.ImportProduct", "ImportProduct")
                        .WithMany("ReceiptProducts")
                        .HasForeignKey("ImportProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportProduct");
                });

            modelBuilder.Entity("BusinessObject.Models.Entity.ImportProduct", b =>
                {
                    b.Navigation("ReceiptProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
